NZWalks.UI/Models/DTO/RegionDto.cs
using System.ComponentModel.DataAnnotations;

namespace NZWalks.UI.Models.DTO
{
    public class RegionDto
    {
        public Guid Id { get; set; }

        [Required]
        [MaxLength(3, ErrorMessage = "length must not be more than 3 characters")]
        [MinLength(3, ErrorMessage = "length must not be less than 3 characters")]
        public string Code { get; set; }
        [Required]
        [MaxLength(100, ErrorMessage = "length must not be more than 100 characters")]
        public string Name { get; set; }

        public string? RegionImageUrl { get; set; }
    }
}

NZWalks.UI/Models/ErrorViewModel.cs
namespace NZWalks.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NZWalks.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NZWalks.UI.Models;
using System.Diagnostics;

namespace NZWalks.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NZWalks.UI/Controllers/RegionsController.cs
using Microsoft.AspNetCore.Mvc;

namespace NZWalks.UI.Controllers
{
    public class RegionsController : Controller
    {
        private readonly IHttpClientFactory httpClient;
        private readonly IConfiguration configuration;
        public RegionsController(IHttpClientFactory _httpClient, IConfiguration _configuration)
        {
            this.httpClient = _httpClient;
            this.configuration = _configuration;
        }
        public async Task<IActionResult>Index()
        {
            //Get region url from appsettings.json
            var regionUrl = configuration["NZWalksAPIs:Region"];

            
            //Call Regions web API
            var responseMessage = await httpClient.CreateClient().GetAsync(requestUri:regionUrl);
            responseMessage.EnsureSuccessStatusCode();
            //Get all regions
            var regions = await responseMessage.Content.ReadFromJsonAsync<IEnumerable<NZWalks.UI.Models.DTO.RegionDto>>();
            //Pass the data to the view
            return View(regions);
        }
    }
}

NZWalks.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NZWalks.UI/Views/Regions/Index.cshtml
@model IEnumerable<RegionDto>

<h1>Regions</h1>

<table class="table table-bordered">
	<thead>
	<tr>
		<th>ID</th>
		<th>Code</th>
		<th>Name</th>
	</tr>
	</thead>
	<tbody>
		@foreach (var region in Model)
		{
			<tr>
				<td>@region.Id</td>
				<td>@region.Code</td>
				<td>@region.Name</td>
			</tr>
		}
	</tbody>
</table>

NZWalks.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NZWalks.UI</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NZWalks.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NZWalks.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
	                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
	                        <a class="nav-link text-dark" asp-area="" asp-controller="Regions" asp-action="Index">Regions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - NZWalks.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>